var deployJava=function(){var c=["id","class","title","style"];"classid codebase codetype data type archive declare standby height width usemap name tabindex align border hspace vspace".split(" ").concat(c,["lang","dir"],"onclick ondblclick onmousedown onmouseup onmouseover onmousemove onmouseout onkeypress onkeydown onkeyup".split(" "));var h="codebase code name archive object width height alt align hspace vspace".split(" ").concat(c),b,m={debug:null,firefoxJavaVersion:null,myInterval:null,preInstallJREList:null,
returnPage:null,brand:null,locale:null,installType:null,EAInstallEnabled:!1,EarlyAccessURL:null,getJavaURL:"http://java.sun.com/webapps/getjava/BrowserRedirect?host\x3djava.com",appleRedirectPage:"http://www.apple.com/support/downloads/",oldMimeType:"application/npruntime-scriptable-plugin;DeploymentToolkit",mimeType:"application/java-deployment-toolkit",launchButtonPNG:"http://java.sun.com/products/jfc/tsc/articles/swing2d/webstart.png",browserName:null,browserName2:null,getJREs:function(){var a=
[];if(this.isPluginInstalled()){var f=this.getPlugin().jvms;for(b=0;b<f.getLength();b++)a[b]=f.get(b).version}else f=this.getBrowser(),"MSIE"===f?this.testUsingActiveX("1.7.0")?a[0]="1.7.0":this.testUsingActiveX("1.6.0")?a[0]="1.6.0":this.testUsingActiveX("1.5.0")?a[0]="1.5.0":this.testUsingActiveX("1.4.2")?a[0]="1.4.2":this.testForMSVM()&&(a[0]="1.1"):"Netscape Family"===f&&(this.getJPIVersionUsingMimeType(),null!==this.firefoxJavaVersion?a[0]=this.firefoxJavaVersion:this.testUsingMimeTypes("1.7")?
a[0]="1.7.0":this.testUsingMimeTypes("1.6")?a[0]="1.6.0":this.testUsingMimeTypes("1.5")?a[0]="1.5.0":this.testUsingMimeTypes("1.4.2")?a[0]="1.4.2":"Safari"===this.browserName2&&(this.testUsingPluginsArray("1.7.0")?a[0]="1.7.0":this.testUsingPluginsArray("1.6")?a[0]="1.6.0":this.testUsingPluginsArray("1.5")?a[0]="1.5.0":this.testUsingPluginsArray("1.4.2")&&(a[0]="1.4.2")));if(this.debug)for(b=0;b<a.length;++b)alert("We claim to have detected Java SE "+a[b]);return a},installJRE:function(a,b){return this.isPluginInstalled()?
this.getPlugin().installJRE(a,b)?(this.refresh(),null!==this.returnPage&&(document.location=this.returnPage),!0):!1:this.installLatestJRE()},installLatestJRE:function(a){if(this.isPluginInstalled())return this.getPlugin().installLatestJRE(a)?(this.refresh(),null!==this.returnPage&&(document.location=this.returnPage),!0):!1;a=this.getBrowser();var b=navigator.platform.toLowerCase();if("true"===this.EAInstallEnabled&&-1!==b.indexOf("win")&&null!==this.EarlyAccessURL)this.preInstallJREList=this.getJREs(),
null!==this.returnPage&&(this.myInterval=setInterval("deployJava.poll()",3E3)),location.href=this.EarlyAccessURL;else{if("MSIE"===a)return this.IEInstall();if("Netscape Family"===a&&-1!==b.indexOf("win32"))return this.FFInstall();location.href=this.getJavaURL+(null!==this.returnPage?"\x26returnPage\x3d"+this.returnPage:"")+(null!==this.locale?"\x26locale\x3d"+this.locale:"")+(null!==this.brand?"\x26brand\x3d"+this.brand:"")}return!1},runApplet:function(a,b,d){if("undefined"===d||null===d)d="1.1";
var e=d.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");null===this.returnPage&&(this.returnPage=document.location);null!==e?"?"!==this.getBrowser()&&"Safari"!==this.browserName2?this.versionCheck(d+"+")?this.writeAppletTag(a,b):this.installJRE(d+"+")&&this.writeAppletTag(a,b):this.writeAppletTag(a,b):this.debug&&alert("Invalid minimumVersion argument to runApplet():"+d)},writeAppletTag:function(a,f){var d="\x3capplet ",e="",c=!0;if(null===f||"object"!==typeof f)f={};for(var g in a){var k;
a:{k=h;var m=g.toLowerCase(),n=k.length;for(b=0;b<n;b++)if(k[b]===m){k=!0;break a}k=!1}k?(d+=" "+g+'\x3d"'+a[g]+'"',"code"===g&&(c=!1)):f[g]=a[g]}g=!1;for(var l in f){"codebase_lookup"===l&&(g=!0);if("object"===l||"java_object"===l||"java_code"===l)c=!1;e+='\x3cparam name\x3d"'+l+'" value\x3d"'+f[l]+'"/\x3e'}g||(e+='\x3cparam name\x3d"codebase_lookup" value\x3d"false"/\x3e');c&&(d+=' code\x3d"dummy"');document.write(d+"\x3e\n"+e+"\n\x3c/applet\x3e")},versionCheck:function(a){index=0;var f=a.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?(\\*|\\+)?$");
if(null!==f){a=!0;var d=[];for(b=1;b<f.length;++b)"string"===typeof f[b]&&""!==f[b]&&(d[index]=f[b],index++);"+"===d[d.length-1]?(a=!1,d.length--):"*"===d[d.length-1]&&d.length--;f=this.getJREs();for(b=0;b<f.length;++b)if(this.compareVersionToPattern(f[b],d,a))return!0}else alert("Invalid versionPattern passed to versionCheck: "+a);return!1},isWebStartInstalled:function(a){if("?"===this.getBrowser()||"Safari"===this.browserName2)return!0;if("undefined"===a||null===a)a="1.4.2";var b=!1;null!==a.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$")?
b=this.versionCheck(a+"+"):(this.debug&&alert("Invalid minimumVersion argument to isWebStartInstalled(): "+a),b=this.versionCheck("1.4.2+"));return b},getJPIVersionUsingMimeType:function(){for(b=0;b<navigator.mimeTypes.length;++b){var a=navigator.mimeTypes[b].type.match(/^application\/x-java-applet;jpi-version=(.*)$/);if(null!==a&&(this.firefoxJavaVersion=a[1],"Opera"!==this.browserName2))break}},launchWebStartApplication:function(a){navigator.userAgent.toLowerCase();this.getJPIVersionUsingMimeType();
if(!1===this.isWebStartInstalled("1.7.0")&&(!1===this.installJRE("1.7.0+")||!1===this.isWebStartInstalled("1.7.0")))return!1;var b=null;document.documentURI&&(b=document.documentURI);null===b&&(b=document.URL);var d=this.getBrowser(),c;"MSIE"===d?c='\x3cobject classid\x3d"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" width\x3d"0" height\x3d"0"\x3e\x3cPARAM name\x3d"launchjnlp" value\x3d"'+a+'"\x3e\x3cPARAM name\x3d"docbase" value\x3d"'+b+'"\x3e\x3c/object\x3e':"Netscape Family"===d&&(c='\x3cembed type\x3d"application/x-java-applet;jpi-version\x3d'+
this.firefoxJavaVersion+'" width\x3d"0" height\x3d"0" launchjnlp\x3d"'+a+'"docbase\x3d"'+b+'" /\x3e');"undefined"===document.body||null===document.body?(document.write(c),document.location=b):(a=document.createElement("div"),a.id="div1",a.style.position="relative",a.style.left="-10000px",a.style.margin="0px auto",a.className="dynamicDiv",a.innerHTML=c,document.body.appendChild(a))},createWebStartLaunchButtonEx:function(a,b){null===this.returnPage&&(this.returnPage=a);document.write('\x3ca href\x3d"'+
("javascript:deployJava.launchWebStartApplication('"+a+"');")+'" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"'+this.launchButtonPNG+'" border\x3d"0" /\x3e\x3c/a\x3e')},createWebStartLaunchButton:function(a,b){null===this.returnPage&&(this.returnPage=a);document.write('\x3ca href\x3d"'+("javascript:if (!deployJava.isWebStartInstalled(\x26quot;"+b+"\x26quot;)) {if (deployJava.installLatestJRE()) {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}} else {if (deployJava.launch(\x26quot;"+
a+"\x26quot;)) {}}")+'" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"'+this.launchButtonPNG+'" border\x3d"0" /\x3e\x3c/a\x3e')},launch:function(a){document.location=a;return!0},isPluginInstalled:function(){var a=this.getPlugin();return a&&a.jvms?!0:!1},isAutoUpdateEnabled:function(){return this.isPluginInstalled()?this.getPlugin().isAutoUpdateEnabled():!1},setAutoUpdateEnabled:function(){return this.isPluginInstalled()?this.getPlugin().setAutoUpdateEnabled():!1},setInstallerType:function(a){this.installType=
a;return this.isPluginInstalled()?this.getPlugin().setInstallerType(a):!1},setAdditionalPackages:function(a){return this.isPluginInstalled()?this.getPlugin().setAdditionalPackages(a):!1},setEarlyAccess:function(a){this.EAInstallEnabled=a},isPlugin2:function(){if(this.isPluginInstalled()&&this.versionCheck("1.6.0_10+"))try{return this.getPlugin().isPlugin2()}catch(a){}return!1},allowPlugin:function(){this.getBrowser();return"Safari"!==this.browserName2&&"Opera"!==this.browserName2},getPlugin:function(){var a=
null;this.allowPlugin()&&(a=document.getElementById("deployJavaPlugin"));return a},compareVersionToPattern:function(a,c,d){var e=a.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");if(null!==e){index=0;a=[];for(b=1;b<e.length;++b)"string"===typeof e[b]&&""!==e[b]&&(a[index]=e[b],index++);e=Math.min(a.length,c.length);if(d)for(b=0;b<e;++b){if(a[b]!==c[b])return!1}else for(b=0;b<e;++b){if(a[b]<c[b])return!1;if(a[b]>c[b])break}return!0}return!1},getBrowser:function(){if(null===this.browserName){var a=
navigator.userAgent.toLowerCase();this.debug&&alert("userAgent -\x3e "+a);-1!==a.indexOf("msie")?this.browserName2=this.browserName="MSIE":-1!==a.indexOf("iphone")?(this.browserName="Netscape Family",this.browserName2="iPhone"):-1!==a.indexOf("firefox")?(this.browserName="Netscape Family",this.browserName2="Firefox"):-1!==a.indexOf("chrome")?(this.browserName="Netscape Family",this.browserName2="Chrome"):-1!==a.indexOf("safari")?(this.browserName="Netscape Family",this.browserName2="Safari"):-1!==
a.indexOf("mozilla")?(this.browserName="Netscape Family",this.browserName2="Other"):-1!==a.indexOf("opera")?(this.browserName="Netscape Family",this.browserName2="Opera"):(this.browserName="?",this.browserName2="unknown");this.debug&&alert("Detected browser name:"+this.browserName+", "+this.browserName2)}return this.browserName},testUsingActiveX:function(a){a="JavaWebStart.isInstalled."+a+".0";if(!ActiveXObject)return this.debug&&alert("Browser claims to be IE, but no ActiveXObject object?"),!1;try{return null!==
new ActiveXObject(a)}catch(b){return!1}},testForMSVM:function(){if("undefined"!==typeof oClientCaps){var a=oClientCaps.getComponentVersion("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}","ComponentID");return""===a||"5,0,5000,0"===a?!1:!0}return!1},testUsingMimeTypes:function(a){if(!navigator.mimeTypes)return this.debug&&alert("Browser claims to be Netscape family, but no mimeTypes[] array?"),!1;for(b=0;b<navigator.mimeTypes.length;++b){s=navigator.mimeTypes[b].type;var c=s.match(/^application\/x-java-applet\x3Bversion=(1\.8|1\.7|1\.6|1\.5|1\.4\.2)$/);
if(null!==c&&this.compareVersions(c[1],a))return!0}return!1},testUsingPluginsArray:function(a){if(!navigator.plugins||!navigator.plugins.length)return!1;var c=navigator.platform.toLowerCase();for(b=0;b<navigator.plugins.length;++b)if(s=navigator.plugins[b].description,-1!==s.search(/^Java Switchable Plug-in (Cocoa)/)){if(this.compareVersions("1.5.0",a))return!0}else if(-1!==s.search(/^Java/)&&-1!==c.indexOf("win")&&(this.compareVersions("1.5.0",a)||this.compareVersions("1.6.0",a)))return!0;return this.compareVersions("1.5.0",
a)?!0:!1},IEInstall:function(){location.href=this.getJavaURL+(null!==this.returnPage?"\x26returnPage\x3d"+this.returnPage:"")+(null!==this.locale?"\x26locale\x3d"+this.locale:"")+(null!==this.brand?"\x26brand\x3d"+this.brand:"");return!1},done:function(a,b){},FFInstall:function(){location.href=this.getJavaURL+(null!==this.returnPage?"\x26returnPage\x3d"+this.returnPage:"")+(null!==this.locale?"\x26locale\x3d"+this.locale:"")+(null!==this.brand?"\x26brand\x3d"+this.brand:"")+(null!==this.installType?
"\x26type\x3d"+this.installType:"");return!1},compareVersions:function(a,c){var d=a.split("."),e=c.split(".");for(b=0;b<d.length;++b)d[b]=Number(d[b]);for(b=0;b<e.length;++b)e[b]=Number(e[b]);2===d.length&&(d[2]=0);return d[0]>e[0]?!0:d[0]<e[0]?!1:d[1]>e[1]?!0:d[1]<e[1]?!1:d[2]>e[2]?!0:d[2]<e[2]?!1:!0},enableAlerts:function(){this.browserName=null;this.debug=!0},poll:function(){this.refresh();var a=this.getJREs();0===this.preInstallJREList.length&&0!==a.length&&(clearInterval(this.myInterval),null!==
this.returnPage&&(location.href=this.returnPage));0!==this.preInstallJREList.length&&0!==a.length&&this.preInstallJREList[0]!==a[0]&&(clearInterval(this.myInterval),null!==this.returnPage&&(location.href=this.returnPage))},writePluginTag:function(){var a=this.getBrowser();"MSIE"===a?document.write('\x3cobject classid\x3d"clsid:CAFEEFAC-DEC7-0000-0000-ABCDEFFEDCBA" id\x3d"deployJavaPlugin" width\x3d"0" height\x3d"0"\x3e\x3c/object\x3e'):"Netscape Family"===a&&this.allowPlugin()&&this.writeEmbedTag()},
refresh:function(){navigator.plugins.refresh(!1);"Netscape Family"===this.getBrowser()&&this.allowPlugin()&&null===document.getElementById("deployJavaPlugin")&&this.writeEmbedTag()},writeEmbedTag:function(){var a=!1;if(null!==navigator.mimeTypes){for(b=0;b<navigator.mimeTypes.length;b++)navigator.mimeTypes[b].type===this.mimeType&&navigator.mimeTypes[b].enabledPlugin&&(document.write('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.mimeType+'" hidden\x3d"true" /\x3e'),a=!0);if(!a)for(b=0;b<navigator.mimeTypes.length;b++)navigator.mimeTypes[b].type===
this.oldMimeType&&navigator.mimeTypes[b].enabledPlugin&&document.write('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.oldMimeType+'" hidden\x3d"true" /\x3e')}}};m.writePluginTag();if(null==m.locale){c=null;if(null==c)try{c=navigator.userLanguage}catch(a){}if(null==c)try{c=navigator.systemLanguage}catch(a){}if(null==c)try{c=navigator.language}catch(a){}null!=c&&(c.replace("-","_"),m.locale=c)}return m}();
YUI.add("bfmodule-footer",function(c){var h=c.namespace("BF.Modules");c.namespace("BF.Const");h.Footer=c.Base.create("Footer",h.Module,[],{initializer:function(){c.log("initializer","debug","bfmodule-footer")},renderUI:function(){this.set("started",!0)},bindUI:function(){this.getModuleConfig("downloadableClient")&&"true"!=this.getModuleConfig("htcmdOnLoadDisabled")&&(window.location="htcmd:pageloaded")},destructor:function(){c.log("destructor","debug","bfmodule-footer")}},{DOM_EVENTS:{click:1,keypress:1},
ATTRS:{}})},"1",{requires:["bfmodule-module"]});
YUI.add("bfmodule-nemid",function(c){var h=c.namespace("BF.Modules");h.NemId=c.Base.create("nemid",h.Module,[],{initializer:function(b){c.log("initializer","debug","bfmodule-nemid");this.i13n=this.get("analytics.i13n")},destructor:function(){c.log("destructor","debug","bfmodule-nemid")},renderUI:function(){c.log("renderUI","debug","bfmodule-nemid");var b;deployJava.versionCheck("1.6+")||(b=this.body.one(".java-warning"))&&b.removeClass("hidden");this._fireI13n({X:"Loaded"});this.set("started",!0)},
bindUI:function(){c.log("bindUI","debug","bfmodule-nemid")},syncUI:function(){c.log("syncUI","debug","bfmodule-nemid")},_fireI13n:function(b){c.log("_fireI13n","debug","bfmodule-login-lightbox");b=b||{};this.i13n.makeCall(this.body,b)}},{})},"1",{requires:["bfmodule-module"]});