'use strict';var deployJava=function(){var d=["id","class","title","style"];"classid codebase codetype data type archive declare standby height width usemap name tabindex align border hspace vspace".split(" ").concat(d,["lang","dir"],"onclick ondblclick onmousedown onmouseup onmouseover onmousemove onmouseout onkeypress onkeydown onkeyup".split(" "));var g="codebase code name archive object width height alt align hspace vspace".split(" ").concat(d),b,m={debug:null,firefoxJavaVersion:null,myInterval:null,
preInstallJREList:null,returnPage:null,brand:null,locale:null,installType:null,EAInstallEnabled:!1,EarlyAccessURL:null,getJavaURL:"http://java.sun.com/webapps/getjava/BrowserRedirect?host\x3djava.com",appleRedirectPage:"http://www.apple.com/support/downloads/",oldMimeType:"application/npruntime-scriptable-plugin;DeploymentToolkit",mimeType:"application/java-deployment-toolkit",launchButtonPNG:"http://java.sun.com/products/jfc/tsc/articles/swing2d/webstart.png",browserName:null,browserName2:null,getJREs:function(){var a=
[];if(this.isPluginInstalled()){var c=this.getPlugin().jvms;for(b=0;b<c.getLength();b++)a[b]=c.get(b).version}else c=this.getBrowser(),"MSIE"===c?this.testUsingActiveX("1.7.0")?a[0]="1.7.0":this.testUsingActiveX("1.6.0")?a[0]="1.6.0":this.testUsingActiveX("1.5.0")?a[0]="1.5.0":this.testUsingActiveX("1.4.2")?a[0]="1.4.2":this.testForMSVM()&&(a[0]="1.1"):"Netscape Family"===c&&(this.getJPIVersionUsingMimeType(),null!==this.firefoxJavaVersion?a[0]=this.firefoxJavaVersion:this.testUsingMimeTypes("1.7")?
a[0]="1.7.0":this.testUsingMimeTypes("1.6")?a[0]="1.6.0":this.testUsingMimeTypes("1.5")?a[0]="1.5.0":this.testUsingMimeTypes("1.4.2")?a[0]="1.4.2":"Safari"===this.browserName2&&(this.testUsingPluginsArray("1.7.0")?a[0]="1.7.0":this.testUsingPluginsArray("1.6")?a[0]="1.6.0":this.testUsingPluginsArray("1.5")?a[0]="1.5.0":this.testUsingPluginsArray("1.4.2")&&(a[0]="1.4.2")));if(this.debug)for(b=0;b<a.length;++b)alert("We claim to have detected Java SE "+a[b]);return a},installJRE:function(a,c){return this.isPluginInstalled()?
this.getPlugin().installJRE(a,c)?(this.refresh(),null!==this.returnPage&&(document.location=this.returnPage),!0):!1:this.installLatestJRE()},installLatestJRE:function(a){if(this.isPluginInstalled())return this.getPlugin().installLatestJRE(a)?(this.refresh(),null!==this.returnPage&&(document.location=this.returnPage),!0):!1;a=this.getBrowser();var c=navigator.platform.toLowerCase();if("true"===this.EAInstallEnabled&&-1!==c.indexOf("win")&&null!==this.EarlyAccessURL)this.preInstallJREList=this.getJREs(),
null!==this.returnPage&&(this.myInterval=setInterval("deployJava.poll()",3E3)),location.href=this.EarlyAccessURL;else{if("MSIE"===a)return this.IEInstall();if("Netscape Family"===a&&-1!==c.indexOf("win32"))return this.FFInstall();location.href=this.getJavaURL+(null!==this.returnPage?"\x26returnPage\x3d"+this.returnPage:"")+(null!==this.locale?"\x26locale\x3d"+this.locale:"")+(null!==this.brand?"\x26brand\x3d"+this.brand:"")}return!1},runApplet:function(a,c,e){if("undefined"===e||null===e)e="1.1";
var f=e.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");null===this.returnPage&&(this.returnPage=document.location);null!==f?"?"!==this.getBrowser()&&"Safari"!==this.browserName2?this.versionCheck(e+"+")?this.writeAppletTag(a,c):this.installJRE(e+"+")&&this.writeAppletTag(a,c):this.writeAppletTag(a,c):this.debug&&alert("Invalid minimumVersion argument to runApplet():"+e)},writeAppletTag:function(a,c){var e="\x3capplet ",f="",n=!0;if(null===c||"object"!==typeof c)c={};for(var h in a){a:{var l=
g;var p=h.toLowerCase(),q=l.length;for(b=0;b<q;b++)if(l[b]===p){l=!0;break a}l=!1}l?(e+=" "+h+'\x3d"'+a[h]+'"',"code"===h&&(n=!1)):c[h]=a[h]}a=!1;for(var k in c){"codebase_lookup"===k&&(a=!0);if("object"===k||"java_object"===k||"java_code"===k)n=!1;f+='\x3cparam name\x3d"'+k+'" value\x3d"'+c[k]+'"/\x3e'}a||(f+='\x3cparam name\x3d"codebase_lookup" value\x3d"false"/\x3e');n&&(e+=' code\x3d"dummy"');document.write(e+"\x3e\n"+f+"\n\x3c/applet\x3e")},versionCheck:function(a){index=0;var c=a.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?(\\*|\\+)?$");
if(null!==c){a=!0;var e=[];for(b=1;b<c.length;++b)"string"===typeof c[b]&&""!==c[b]&&(e[index]=c[b],index++);"+"===e[e.length-1]?(a=!1,e.length--):"*"===e[e.length-1]&&e.length--;c=this.getJREs();for(b=0;b<c.length;++b)if(this.compareVersionToPattern(c[b],e,a))return!0}else alert("Invalid versionPattern passed to versionCheck: "+a);return!1},isWebStartInstalled:function(a){if("?"===this.getBrowser()||"Safari"===this.browserName2)return!0;if("undefined"===a||null===a)a="1.4.2";null!==a.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$")?
a=this.versionCheck(a+"+"):(this.debug&&alert("Invalid minimumVersion argument to isWebStartInstalled(): "+a),a=this.versionCheck("1.4.2+"));return a},getJPIVersionUsingMimeType:function(){for(b=0;b<navigator.mimeTypes.length;++b){var a=navigator.mimeTypes[b].type.match(/^application\/x-java-applet;jpi-version=(.*)$/);if(null!==a&&(this.firefoxJavaVersion=a[1],"Opera"!==this.browserName2))break}},launchWebStartApplication:function(a){navigator.userAgent.toLowerCase();this.getJPIVersionUsingMimeType();
if(!1===this.isWebStartInstalled("1.7.0")&&(!1===this.installJRE("1.7.0+")||!1===this.isWebStartInstalled("1.7.0")))return!1;var c=null;document.documentURI&&(c=document.documentURI);null===c&&(c=document.URL);var e=this.getBrowser(),f;"MSIE"===e?f='\x3cobject classid\x3d"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" width\x3d"0" height\x3d"0"\x3e\x3cPARAM name\x3d"launchjnlp" value\x3d"'+a+'"\x3e\x3cPARAM name\x3d"docbase" value\x3d"'+c+'"\x3e\x3c/object\x3e':"Netscape Family"===e&&(f='\x3cembed type\x3d"application/x-java-applet;jpi-version\x3d'+
this.firefoxJavaVersion+'" width\x3d"0" height\x3d"0" launchjnlp\x3d"'+a+'"docbase\x3d"'+c+'" /\x3e');"undefined"===document.body||null===document.body?(document.write(f),document.location=c):(a=document.createElement("div"),a.id="div1",a.style.position="relative",a.style.left="-10000px",a.style.margin="0px auto",a.className="dynamicDiv",a.innerHTML=f,document.body.appendChild(a))},createWebStartLaunchButtonEx:function(a,c){null===this.returnPage&&(this.returnPage=a);document.write("\x3ca href\x3d\"javascript:deployJava.launchWebStartApplication('"+
(a+'\');" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"')+this.launchButtonPNG+'" border\x3d"0" /\x3e\x3c/a\x3e')},createWebStartLaunchButton:function(a,c){null===this.returnPage&&(this.returnPage=a);document.write('\x3ca href\x3d"javascript:if (!deployJava.isWebStartInstalled(\x26quot;'+(c+"\x26quot;)) {if (deployJava.installLatestJRE()) {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}} else {if (deployJava.launch(\x26quot;"+a+'\x26quot;)) {}}" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"')+
this.launchButtonPNG+'" border\x3d"0" /\x3e\x3c/a\x3e')},launch:function(a){document.location=a;return!0},isPluginInstalled:function(){var a=this.getPlugin();return a&&a.jvms?!0:!1},isAutoUpdateEnabled:function(){return this.isPluginInstalled()?this.getPlugin().isAutoUpdateEnabled():!1},setAutoUpdateEnabled:function(){return this.isPluginInstalled()?this.getPlugin().setAutoUpdateEnabled():!1},setInstallerType:function(a){this.installType=a;return this.isPluginInstalled()?this.getPlugin().setInstallerType(a):
!1},setAdditionalPackages:function(a){return this.isPluginInstalled()?this.getPlugin().setAdditionalPackages(a):!1},setEarlyAccess:function(a){this.EAInstallEnabled=a},isPlugin2:function(){if(this.isPluginInstalled()&&this.versionCheck("1.6.0_10+"))try{return this.getPlugin().isPlugin2()}catch(a){}return!1},allowPlugin:function(){this.getBrowser();return"Safari"!==this.browserName2&&"Opera"!==this.browserName2},getPlugin:function(){var a=null;this.allowPlugin()&&(a=document.getElementById("deployJavaPlugin"));
return a},compareVersionToPattern:function(a,c,e){var f=a.match("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");if(null!==f){index=0;a=[];for(b=1;b<f.length;++b)"string"===typeof f[b]&&""!==f[b]&&(a[index]=f[b],index++);f=Math.min(a.length,c.length);if(e)for(b=0;b<f;++b){if(a[b]!==c[b])return!1}else for(b=0;b<f;++b){if(a[b]<c[b])return!1;if(a[b]>c[b])break}return!0}return!1},getBrowser:function(){if(null===this.browserName){var a=navigator.userAgent.toLowerCase();this.debug&&alert("userAgent -\x3e "+
a);-1!==a.indexOf("msie")?this.browserName2=this.browserName="MSIE":-1!==a.indexOf("iphone")?(this.browserName="Netscape Family",this.browserName2="iPhone"):-1!==a.indexOf("firefox")?(this.browserName="Netscape Family",this.browserName2="Firefox"):-1!==a.indexOf("chrome")?(this.browserName="Netscape Family",this.browserName2="Chrome"):-1!==a.indexOf("safari")?(this.browserName="Netscape Family",this.browserName2="Safari"):-1!==a.indexOf("mozilla")?(this.browserName="Netscape Family",this.browserName2=
"Other"):-1!==a.indexOf("opera")?(this.browserName="Netscape Family",this.browserName2="Opera"):(this.browserName="?",this.browserName2="unknown");this.debug&&alert("Detected browser name:"+this.browserName+", "+this.browserName2)}return this.browserName},testUsingActiveX:function(a){a="JavaWebStart.isInstalled."+a+".0";if(!ActiveXObject)return this.debug&&alert("Browser claims to be IE, but no ActiveXObject object?"),!1;try{return null!==new ActiveXObject(a)}catch(c){return!1}},testForMSVM:function(){if("undefined"!==
typeof oClientCaps){var a=oClientCaps.getComponentVersion("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}","ComponentID");return""===a||"5,0,5000,0"===a?!1:!0}return!1},testUsingMimeTypes:function(a){if(!navigator.mimeTypes)return this.debug&&alert("Browser claims to be Netscape family, but no mimeTypes[] array?"),!1;for(b=0;b<navigator.mimeTypes.length;++b){s=navigator.mimeTypes[b].type;var c=s.match(/^application\/x-java-applet\x3Bversion=(1\.8|1\.7|1\.6|1\.5|1\.4\.2)$/);if(null!==c&&this.compareVersions(c[1],
a))return!0}return!1},testUsingPluginsArray:function(a){if(!navigator.plugins||!navigator.plugins.length)return!1;var c=navigator.platform.toLowerCase();for(b=0;b<navigator.plugins.length;++b)if(s=navigator.plugins[b].description,-1!==s.search(/^Java Switchable Plug-in (Cocoa)/)){if(this.compareVersions("1.5.0",a))return!0}else if(-1!==s.search(/^Java/)&&-1!==c.indexOf("win")&&(this.compareVersions("1.5.0",a)||this.compareVersions("1.6.0",a)))return!0;return this.compareVersions("1.5.0",a)?!0:!1},
IEInstall:function(){location.href=this.getJavaURL+(null!==this.returnPage?"\x26returnPage\x3d"+this.returnPage:"")+(null!==this.locale?"\x26locale\x3d"+this.locale:"")+(null!==this.brand?"\x26brand\x3d"+this.brand:"");return!1},done:function(a,c){},FFInstall:function(){location.href=this.getJavaURL+(null!==this.returnPage?"\x26returnPage\x3d"+this.returnPage:"")+(null!==this.locale?"\x26locale\x3d"+this.locale:"")+(null!==this.brand?"\x26brand\x3d"+this.brand:"")+(null!==this.installType?"\x26type\x3d"+
this.installType:"");return!1},compareVersions:function(a,c){a=a.split(".");c=c.split(".");for(b=0;b<a.length;++b)a[b]=Number(a[b]);for(b=0;b<c.length;++b)c[b]=Number(c[b]);2===a.length&&(a[2]=0);return a[0]>c[0]?!0:a[0]<c[0]?!1:a[1]>c[1]?!0:a[1]<c[1]?!1:a[2]>c[2]?!0:a[2]<c[2]?!1:!0},enableAlerts:function(){this.browserName=null;this.debug=!0},poll:function(){this.refresh();var a=this.getJREs();0===this.preInstallJREList.length&&0!==a.length&&(clearInterval(this.myInterval),null!==this.returnPage&&
(location.href=this.returnPage));0!==this.preInstallJREList.length&&0!==a.length&&this.preInstallJREList[0]!==a[0]&&(clearInterval(this.myInterval),null!==this.returnPage&&(location.href=this.returnPage))},writePluginTag:function(){var a=this.getBrowser();"MSIE"===a?document.write('\x3cobject classid\x3d"clsid:CAFEEFAC-DEC7-0000-0000-ABCDEFFEDCBA" id\x3d"deployJavaPlugin" width\x3d"0" height\x3d"0"\x3e\x3c/object\x3e'):"Netscape Family"===a&&this.allowPlugin()&&this.writeEmbedTag()},refresh:function(){navigator.plugins.refresh(!1);
"Netscape Family"===this.getBrowser()&&this.allowPlugin()&&null===document.getElementById("deployJavaPlugin")&&this.writeEmbedTag()},writeEmbedTag:function(){var a=!1;if(null!==navigator.mimeTypes){for(b=0;b<navigator.mimeTypes.length;b++)navigator.mimeTypes[b].type===this.mimeType&&navigator.mimeTypes[b].enabledPlugin&&(document.write('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.mimeType+'" hidden\x3d"true" /\x3e'),a=!0);if(!a)for(b=0;b<navigator.mimeTypes.length;b++)navigator.mimeTypes[b].type===
this.oldMimeType&&navigator.mimeTypes[b].enabledPlugin&&document.write('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.oldMimeType+'" hidden\x3d"true" /\x3e')}}};m.writePluginTag();if(null==m.locale){d=null;if(null==d)try{d=navigator.userLanguage}catch(a){}if(null==d)try{d=navigator.systemLanguage}catch(a){}if(null==d)try{d=navigator.language}catch(a){}null!=d&&(d.replace("-","_"),m.locale=d)}return m}();
YUI.add("bfmodule-footer",function(d){var g=d.namespace("BF.Modules");d.namespace("BF.Const");g.Footer=d.Base.create("Footer",g.Module,[],{initializer:function(){d.log("initializer","debug","bfmodule-footer")},renderUI:function(){this.set("started",!0)},bindUI:function(){this.getModuleConfig("downloadableClient")&&"true"!=this.getModuleConfig("htcmdOnLoadDisabled")&&(window.location="htcmd:pageloaded")},destructor:function(){d.log("destructor","debug","bfmodule-footer")}},{DOM_EVENTS:{click:1,keypress:1},
ATTRS:{}})},"1",{requires:["bfmodule-module"]});
YUI.add("bfmodule-nemid",function(d){var g=d.namespace("BF.Modules");g.NemId=d.Base.create("nemid",g.Module,[],{initializer:function(b){d.log("initializer","debug","bfmodule-nemid");this.i13n=this.get("analytics.i13n")},destructor:function(){d.log("destructor","debug","bfmodule-nemid")},renderUI:function(){d.log("renderUI","debug","bfmodule-nemid");var b;deployJava.versionCheck("1.6+")||(b=this.body.one(".java-warning"))&&b.removeClass("hidden");this._fireI13n({X:"Loaded"});this.set("started",!0)},
bindUI:function(){d.log("bindUI","debug","bfmodule-nemid")},syncUI:function(){d.log("syncUI","debug","bfmodule-nemid")},_fireI13n:function(b){d.log("_fireI13n","debug","bfmodule-login-lightbox");b=b||{};this.i13n.makeCall(this.body,b)}},{})},"1",{requires:["bfmodule-module"]});