var c=!0,e=null,h=!1,u=function(){var d=["id","class","title","style"];"classid codebase codetype data type archive declare standby height width usemap name tabindex align border hspace vspace".split(" ").ca(d,["lang","dir"],"onclick ondblclick onmousedown onmouseup onmouseover onmousemove onmouseout onkeypress onkeydown onkeyup".split(" "));var m="codebase code name archive object width height alt align hspace vspace".split(" ").ca(d),b,r={h:e,u:e,H:e,w:e,b:e,m:e,k:e,G:e,K:h,L:e,E:"http://java.sun.com/webapps/getjava/BrowserRedirect?host\x3djava.com",
Ha:"http://www.apple.com/support/downloads/",S:"application/npruntime-scriptable-plugin;DeploymentToolkit",Q:"application/java-deployment-toolkit",P:"http://java.sun.com/products/jfc/tsc/articles/swing2d/webstart.png",d:e,c:e,D:function(){var a=[];if(this.j()){var k=this.f().oa;for(b=0;b<k.Qa();b++)a[b]=k.ha(b).jb}else k=this.i(),"MSIE"===k?this.y("1.7.0")?a[0]="1.7.0":this.y("1.6.0")?a[0]="1.6.0":this.y("1.5.0")?a[0]="1.5.0":this.y("1.4.2")?a[0]="1.4.2":this.ya()&&(a[0]="1.1"):"Netscape Family"===
k&&(this.M(),this.u!==e?a[0]=this.u:this.z("1.7")?a[0]="1.7.0":this.z("1.6")?a[0]="1.6.0":this.z("1.5")?a[0]="1.5.0":this.z("1.4.2")?a[0]="1.4.2":"Safari"===this.c&&(this.A("1.7.0")?a[0]="1.7.0":this.A("1.6")?a[0]="1.6.0":this.A("1.5")?a[0]="1.5.0":this.A("1.4.2")&&(a[0]="1.4.2")));if(this.h)for(b=0;b<a.a;++b)alert("We claim to have detected Java SE "+a[b]);return a},F:function(a,b){return this.j()?this.f().F(a,b)?(this.x(),this.b!==e&&(document.q=this.b),c):h:this.N()},N:function(a){if(this.j())return this.f().N(a)?
(this.x(),this.b!==e&&(document.q=this.b),c):h;a=this.i();var b=navigator.pa.B();if("true"===this.K&&-1!==b.g("win")&&this.L!==e)this.w=this.D(),this.b!==e&&(this.H=setInterval("deployJava.poll()",3E3)),location.p=this.L;else{if("MSIE"===a)return this.X();if("Netscape Family"===a&&-1!==b.g("win32"))return this.W();location.p=this.E+(this.b!==e?"\x26returnPage\x3d"+this.b:"")+(this.k!==e?"\x26locale\x3d"+this.k:"")+(this.m!==e?"\x26brand\x3d"+this.m:"")}return h},eb:function(a,b,f){if("undefined"===
f||f===e)f="1.1";var g=f.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");this.b===e&&(this.b=document.q);g!==e?"?"!==this.i()&&"Safari"!==this.c?this.s(f+"+")?this.J(a,b):this.F(f+"+")&&this.J(a,b):this.J(a,b):this.h&&alert("Invalid minimumVersion argument to runApplet():"+f)},J:function(a,k){var f="\x3capplet ",g="",d=c;if(e===k||"object"!==typeof k)k={};for(var l in a){var n;a:{n=m;var r=l.B(),t=n.a;for(b=0;b<t;b++)if(n[b]===r){n=c;break a}n=h}n?(f+=" "+l+'\x3d"'+a[l]+'"',"code"===l&&(d=h)):
k[l]=a[l]}l=h;for(var p in k){"codebase_lookup"===p&&(l=c);if("object"===p||"java_object"===p||"java_code"===p)d=h;g+='\x3cparam name\x3d"'+p+'" value\x3d"'+k[p]+'"/\x3e'}l||(g+='\x3cparam name\x3d"codebase_lookup" value\x3d"false"/\x3e');d&&(f+=' code\x3d"dummy"');document.n(f+"\x3e\n"+g+"\n\x3c/applet\x3e")},s:function(a){index=0;var k=a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?(\\*|\\+)?$");if(k!==e){a=c;var f=[];for(b=1;b<k.a;++b)"string"===typeof k[b]&&""!==k[b]&&(f[index]=k[b],index++);
"+"===f[f.a-1]?(a=h,f.a--):"*"===f[f.a-1]&&f.a--;k=this.D();for(b=0;b<k.a;++b)if(this.ba(k[b],f,a))return c}else alert("Invalid versionPattern passed to versionCheck: "+a);return h},O:function(a){if("?"===this.i()||"Safari"===this.c)return c;if("undefined"===a||a===e)a="1.4.2";var b=h;a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$")!==e?b=this.s(a+"+"):(this.h&&alert("Invalid minimumVersion argument to isWebStartInstalled(): "+a),b=this.s("1.4.2+"));return b},M:function(){for(b=0;b<navigator.e.a;++b){var a=
navigator.e[b].I.r(/^application\/x-java-applet;jpi-version=(.*)$/);if(a!==e&&(this.u=a[1],"Opera"!==this.c))break}},Va:function(a){navigator.za.B();this.M();if(this.O("1.7.0")===h&&(this.F("1.7.0+")===h||this.O("1.7.0")===h))return h;var b=e;document.fa&&(b=document.fa);b===e&&(b=document.Ea);var f=this.i(),d;"MSIE"===f?d='\x3cobject classid\x3d"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" width\x3d"0" height\x3d"0"\x3e\x3cPARAM name\x3d"launchjnlp" value\x3d"'+a+'"\x3e\x3cPARAM name\x3d"docbase" value\x3d"'+
b+'"\x3e\x3c/object\x3e':"Netscape Family"===f&&(d='\x3cembed type\x3d"application/x-java-applet;jpi-version\x3d'+this.u+'" width\x3d"0" height\x3d"0" launchjnlp\x3d"'+a+'"docbase\x3d"'+b+'" /\x3e');"undefined"===document.t||document.t===e?(document.n(d),document.q=b):(a=document.Ja("div"),a.Ra="div1",a.T.bb="relative",a.T.Wa="-10000px",a.T.Ya="0px auto",a.Ia="dynamicDiv",a.Sa=d,document.t.Ga(a))},La:function(a){this.b===e&&(this.b=a);document.n('\x3ca href\x3d"'+("javascript:deployJava.launchWebStartApplication('"+
a+"');")+'" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"'+this.P+'" border\x3d"0" /\x3e\x3c/a\x3e')},Ka:function(a,b){this.b===e&&(this.b=a);document.n('\x3ca href\x3d"'+("javascript:if (!deployJava.isWebStartInstalled(\x26quot;"+b+"\x26quot;)) {if (deployJava.installLatestJRE()) {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}} else {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}")+'" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"'+this.P+
'" border\x3d"0" /\x3e\x3c/a\x3e')},Ua:function(a){document.q=a;return c},j:function(){var a=this.f();return a&&a.oa?c:h},ma:function(){return this.j()?this.f().ma():h},va:function(){return this.j()?this.f().va():h},wa:function(a){this.G=a;return this.j()?this.f().wa(a):h},ua:function(a){return this.j()?this.f().ua(a):h},fb:function(a){this.K=a},na:function(){if(this.j()&&this.s("1.6.0_10+"))try{return this.f().na()}catch(a){}return h},C:function(){this.i();return"Safari"!==this.c&&"Opera"!==this.c},
f:function(){var a=e;this.C()&&(a=document.ia("deployJavaPlugin"));return a},ba:function(a,d,f){var g=a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");if(g!==e){index=0;a=[];for(b=1;b<g.a;++b)"string"===typeof g[b]&&""!==g[b]&&(a[index]=g[b],index++);g=Math.Za(a.a,d.a);if(f)for(b=0;b<g;++b){if(a[b]!==d[b])return h}else for(b=0;b<g;++b){if(a[b]<d[b])return h;if(a[b]>d[b])break}return c}return h},i:function(){if(this.d===e){var a=navigator.za.B();this.h&&alert("userAgent -\x3e "+a);-1!==a.g("msie")?
this.c=this.d="MSIE":-1!==a.g("iphone")?(this.d="Netscape Family",this.c="iPhone"):-1!==a.g("firefox")?(this.d="Netscape Family",this.c="Firefox"):-1!==a.g("chrome")?(this.d="Netscape Family",this.c="Chrome"):-1!==a.g("safari")?(this.d="Netscape Family",this.c="Safari"):-1!==a.g("mozilla")?(this.d="Netscape Family",this.c="Other"):-1!==a.g("opera")?(this.d="Netscape Family",this.c="Opera"):(this.d="?",this.c="unknown");this.h&&alert("Detected browser name:"+this.d+", "+this.c)}return this.d},y:function(a){a=
"JavaWebStart.isInstalled."+a+".0";if(!ActiveXObject)return this.h&&alert("Browser claims to be IE, but no ActiveXObject object?"),h;try{return new ActiveXObject(a)!==e}catch(b){return h}},ya:function(){if("undefined"!==typeof oClientCaps){var a=oClientCaps.Pa("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}","ComponentID");return""===a||"5,0,5000,0"===a?h:c}return h},z:function(a){if(!navigator.e)return this.h&&alert("Browser claims to be Netscape family, but no mimeTypes[] array?"),h;for(b=0;b<navigator.e.a;++b){s=
navigator.e[b].I;var d=s.r(/^application\/x-java-applet\x3Bversion=(1\.8|1\.7|1\.6|1\.5|1\.4\.2)$/);if(d!==e&&this.o(d[1],a))return c}return h},A:function(a){if(!navigator.v||!navigator.v.a)return h;var d=navigator.pa.B();for(b=0;b<navigator.v.a;++b)if(s=navigator.v[b].Ma,-1!==s.sa(/^Java Switchable Plug-in (Cocoa)/)){if(this.o("1.5.0",a))return c}else if(-1!==s.sa(/^Java/)&&-1!==d.g("win")&&(this.o("1.5.0",a)||this.o("1.6.0",a)))return c;return this.o("1.5.0",a)?c:h},X:function(){location.p=this.E+
(this.b!==e?"\x26returnPage\x3d"+this.b:"")+(this.k!==e?"\x26locale\x3d"+this.k:"")+(this.m!==e?"\x26brand\x3d"+this.m:"");return h},Na:function(){},W:function(){location.p=this.E+(this.b!==e?"\x26returnPage\x3d"+this.b:"")+(this.k!==e?"\x26locale\x3d"+this.k:"")+(this.m!==e?"\x26brand\x3d"+this.m:"")+(this.G!==e?"\x26type\x3d"+this.G:"");return h},o:function(a,d){var f=a.xa("."),g=d.xa(".");for(b=0;b<f.a;++b)f[b]=Number(f[b]);for(b=0;b<g.a;++b)g[b]=Number(g[b]);2===f.a&&(f[2]=0);return f[0]>g[0]?
c:f[0]<g[0]?h:f[1]>g[1]?c:f[1]<g[1]?h:f[2]>g[2]?c:f[2]<g[2]?h:c},Oa:function(){this.d=e;this.h=c},ab:function(){this.x();var a=this.D();0===this.w.a&&0!==a.a&&(clearInterval(this.H),this.b!==e&&(location.p=this.b));0!==this.w.a&&(0!==a.a&&this.w[0]!==a[0])&&(clearInterval(this.H),this.b!==e&&(location.p=this.b))},Aa:function(){var a=this.i();"MSIE"===a?document.n('\x3cobject classid\x3d"clsid:CAFEEFAC-DEC7-0000-0000-ABCDEFFEDCBA" id\x3d"deployJavaPlugin" width\x3d"0" height\x3d"0"\x3e\x3c/object\x3e'):
"Netscape Family"===a&&this.C()&&this.U()},x:function(){navigator.v.x(h);"Netscape Family"===this.i()&&this.C()&&document.ia("deployJavaPlugin")===e&&this.U()},U:function(){var a=h;if(navigator.e!==e){for(b=0;b<navigator.e.a;b++)navigator.e[b].I===this.Q&&navigator.e[b].ga&&(document.n('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.Q+'" hidden\x3d"true" /\x3e'),a=c);if(!a)for(b=0;b<navigator.e.a;b++)navigator.e[b].I===this.S&&navigator.e[b].ga&&document.n('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+
this.S+'" hidden\x3d"true" /\x3e')}}};r.Aa();if(r.k==e){d=e;if(d==e)try{d=navigator.ib}catch(v){}if(d==e)try{d=navigator.hb}catch(w){}if(d==e)try{d=navigator.Ta}catch(x){}d!=e&&(d.db("-","_"),r.k=d)}return r}();
YUI.$("bfmodule-footer",function(d){var m=d.R("BF.Modules");d.R("BF.Const");m.Ca=d.V.da("Footer",m.Y,[],{la:function(){d.l("initializer","debug","bfmodule-footer")},qa:function(){this.ta("started",c)},aa:function(){this.ja("downloadableClient")&&"true"!=this.ja("htcmdOnLoadDisabled")&&(window.q="htcmd:pageloaded")},ea:function(){d.l("destructor","debug","bfmodule-footer")}},{Ba:{click:1,keypress:1},ATTRS:{}})},"1",{ra:["bfmodule-module"]});
YUI.$("bfmodule-nemid",function(d){var m=d.R("BF.Modules");m.Da=d.V.da("nemid",m.Y,[],{la:function(){d.l("initializer","debug","bfmodule-nemid");this.ka=this.ha("analytics.i13n")},ea:function(){d.l("destructor","debug","bfmodule-nemid")},qa:function(){d.l("renderUI","debug","bfmodule-nemid");var b;u.s("1.6+")||(b=this.t.$a(".java-warning"))&&b.cb("hidden");this.Z({Fa:"Loaded"});this.ta("started",c)},aa:function(){d.l("bindUI","debug","bfmodule-nemid")},gb:function(){d.l("syncUI","debug","bfmodule-nemid")},
Z:function(b){d.l("_fireI13n","debug","bfmodule-login-lightbox");b=b||{};this.ka.Xa(this.t,b)}},{})},"1",{ra:["bfmodule-module"]});