'use strict';var t=function(){var d=["id","class","title","style"];"classid codebase codetype data type archive declare standby height width usemap name tabindex align border hspace vspace".split(" ").ca(d,["lang","dir"],"onclick ondblclick onmousedown onmouseup onmouseover onmousemove onmouseout onkeypress onkeydown onkeyup".split(" "));var g="codebase code name archive object width height alt align hspace vspace".split(" ").ca(d),b,m={h:null,u:null,H:null,w:null,b:null,m:null,k:null,G:null,K:!1,
L:null,E:"http://java.sun.com/webapps/getjava/BrowserRedirect?host\x3djava.com",Ha:"http://www.apple.com/support/downloads/",S:"application/npruntime-scriptable-plugin;DeploymentToolkit",Q:"application/java-deployment-toolkit",P:"http://java.sun.com/products/jfc/tsc/articles/swing2d/webstart.png",d:null,c:null,D:function(){var a=[];if(this.j()){var c=this.f().oa;for(b=0;b<c.Qa();b++)a[b]=c.ha(b).jb}else c=this.i(),"MSIE"===c?this.y("1.7.0")?a[0]="1.7.0":this.y("1.6.0")?a[0]="1.6.0":this.y("1.5.0")?
a[0]="1.5.0":this.y("1.4.2")?a[0]="1.4.2":this.ya()&&(a[0]="1.1"):"Netscape Family"===c&&(this.M(),null!==this.u?a[0]=this.u:this.z("1.7")?a[0]="1.7.0":this.z("1.6")?a[0]="1.6.0":this.z("1.5")?a[0]="1.5.0":this.z("1.4.2")?a[0]="1.4.2":"Safari"===this.c&&(this.A("1.7.0")?a[0]="1.7.0":this.A("1.6")?a[0]="1.6.0":this.A("1.5")?a[0]="1.5.0":this.A("1.4.2")&&(a[0]="1.4.2")));if(this.h)for(b=0;b<a.a;++b)alert("We claim to have detected Java SE "+a[b]);return a},F:function(a,c){return this.j()?this.f().F(a,
c)?(this.x(),null!==this.b&&(document.q=this.b),!0):!1:this.N()},N:function(a){if(this.j())return this.f().N(a)?(this.x(),null!==this.b&&(document.q=this.b),!0):!1;a=this.i();var c=navigator.pa.B();if("true"===this.K&&-1!==c.g("win")&&null!==this.L)this.w=this.D(),null!==this.b&&(this.H=setInterval("deployJava.poll()",3E3)),location.p=this.L;else{if("MSIE"===a)return this.X();if("Netscape Family"===a&&-1!==c.g("win32"))return this.W();location.p=this.E+(null!==this.b?"\x26returnPage\x3d"+this.b:"")+
(null!==this.k?"\x26locale\x3d"+this.k:"")+(null!==this.m?"\x26brand\x3d"+this.m:"")}return!1},eb:function(a,c,e){if("undefined"===e||null===e)e="1.1";var f=e.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");null===this.b&&(this.b=document.q);null!==f?"?"!==this.i()&&"Safari"!==this.c?this.s(e+"+")?this.J(a,c):this.F(e+"+")&&this.J(a,c):this.J(a,c):this.h&&alert("Invalid minimumVersion argument to runApplet():"+e)},J:function(a,c){var e="\x3capplet ",f="",n=!0;if(null===c||"object"!==typeof c)c=
{};for(var h in a){a:{var l=g;var p=h.B(),r=l.a;for(b=0;b<r;b++)if(l[b]===p){l=!0;break a}l=!1}l?(e+=" "+h+'\x3d"'+a[h]+'"',"code"===h&&(n=!1)):c[h]=a[h]}a=!1;for(var k in c){"codebase_lookup"===k&&(a=!0);if("object"===k||"java_object"===k||"java_code"===k)n=!1;f+='\x3cparam name\x3d"'+k+'" value\x3d"'+c[k]+'"/\x3e'}a||(f+='\x3cparam name\x3d"codebase_lookup" value\x3d"false"/\x3e');n&&(e+=' code\x3d"dummy"');document.n(e+"\x3e\n"+f+"\n\x3c/applet\x3e")},s:function(a){index=0;var c=a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?(\\*|\\+)?$");
if(null!==c){a=!0;var e=[];for(b=1;b<c.a;++b)"string"===typeof c[b]&&""!==c[b]&&(e[index]=c[b],index++);"+"===e[e.a-1]?(a=!1,e.a--):"*"===e[e.a-1]&&e.a--;c=this.D();for(b=0;b<c.a;++b)if(this.ba(c[b],e,a))return!0}else alert("Invalid versionPattern passed to versionCheck: "+a);return!1},O:function(a){if("?"===this.i()||"Safari"===this.c)return!0;if("undefined"===a||null===a)a="1.4.2";null!==a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$")?a=this.s(a+"+"):(this.h&&alert("Invalid minimumVersion argument to isWebStartInstalled(): "+
a),a=this.s("1.4.2+"));return a},M:function(){for(b=0;b<navigator.e.a;++b){var a=navigator.e[b].I.r(/^application\/x-java-applet;jpi-version=(.*)$/);if(null!==a&&(this.u=a[1],"Opera"!==this.c))break}},Va:function(a){navigator.za.B();this.M();if(!1===this.O("1.7.0")&&(!1===this.F("1.7.0+")||!1===this.O("1.7.0")))return!1;var c=null;document.fa&&(c=document.fa);null===c&&(c=document.Ea);var e=this.i(),f;"MSIE"===e?f='\x3cobject classid\x3d"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" width\x3d"0" height\x3d"0"\x3e\x3cPARAM name\x3d"launchjnlp" value\x3d"'+
a+'"\x3e\x3cPARAM name\x3d"docbase" value\x3d"'+c+'"\x3e\x3c/object\x3e':"Netscape Family"===e&&(f='\x3cembed type\x3d"application/x-java-applet;jpi-version\x3d'+this.u+'" width\x3d"0" height\x3d"0" launchjnlp\x3d"'+a+'"docbase\x3d"'+c+'" /\x3e');"undefined"===document.t||null===document.t?(document.n(f),document.q=c):(a=document.Ja("div"),a.Ra="div1",a.T.bb="relative",a.T.Wa="-10000px",a.T.Ya="0px auto",a.Ia="dynamicDiv",a.Sa=f,document.t.Ga(a))},La:function(a){null===this.b&&(this.b=a);document.n("\x3ca href\x3d\"javascript:deployJava.launchWebStartApplication('"+
(a+'\');" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"')+this.P+'" border\x3d"0" /\x3e\x3c/a\x3e')},Ka:function(a,c){null===this.b&&(this.b=a);document.n('\x3ca href\x3d"javascript:if (!deployJava.isWebStartInstalled(\x26quot;'+(c+"\x26quot;)) {if (deployJava.installLatestJRE()) {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}} else {if (deployJava.launch(\x26quot;"+a+'\x26quot;)) {}}" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"')+this.P+
'" border\x3d"0" /\x3e\x3c/a\x3e')},Ua:function(a){document.q=a;return!0},j:function(){var a=this.f();return a&&a.oa?!0:!1},ma:function(){return this.j()?this.f().ma():!1},va:function(){return this.j()?this.f().va():!1},wa:function(a){this.G=a;return this.j()?this.f().wa(a):!1},ua:function(a){return this.j()?this.f().ua(a):!1},fb:function(a){this.K=a},na:function(){if(this.j()&&this.s("1.6.0_10+"))try{return this.f().na()}catch(a){}return!1},C:function(){this.i();return"Safari"!==this.c&&"Opera"!==
this.c},f:function(){var a=null;this.C()&&(a=document.ia("deployJavaPlugin"));return a},ba:function(a,c,e){var f=a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");if(null!==f){index=0;a=[];for(b=1;b<f.a;++b)"string"===typeof f[b]&&""!==f[b]&&(a[index]=f[b],index++);f=Math.Za(a.a,c.a);if(e)for(b=0;b<f;++b){if(a[b]!==c[b])return!1}else for(b=0;b<f;++b){if(a[b]<c[b])return!1;if(a[b]>c[b])break}return!0}return!1},i:function(){if(null===this.d){var a=navigator.za.B();this.h&&alert("userAgent -\x3e "+
a);-1!==a.g("msie")?this.c=this.d="MSIE":-1!==a.g("iphone")?(this.d="Netscape Family",this.c="iPhone"):-1!==a.g("firefox")?(this.d="Netscape Family",this.c="Firefox"):-1!==a.g("chrome")?(this.d="Netscape Family",this.c="Chrome"):-1!==a.g("safari")?(this.d="Netscape Family",this.c="Safari"):-1!==a.g("mozilla")?(this.d="Netscape Family",this.c="Other"):-1!==a.g("opera")?(this.d="Netscape Family",this.c="Opera"):(this.d="?",this.c="unknown");this.h&&alert("Detected browser name:"+this.d+", "+this.c)}return this.d},
y:function(a){a="JavaWebStart.isInstalled."+a+".0";if(!ActiveXObject)return this.h&&alert("Browser claims to be IE, but no ActiveXObject object?"),!1;try{return null!==new ActiveXObject(a)}catch(c){return!1}},ya:function(){if("undefined"!==typeof oClientCaps){var a=oClientCaps.Pa("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}","ComponentID");return""===a||"5,0,5000,0"===a?!1:!0}return!1},z:function(a){if(!navigator.e)return this.h&&alert("Browser claims to be Netscape family, but no mimeTypes[] array?"),
!1;for(b=0;b<navigator.e.a;++b){s=navigator.e[b].I;var c=s.r(/^application\/x-java-applet\x3Bversion=(1\.8|1\.7|1\.6|1\.5|1\.4\.2)$/);if(null!==c&&this.o(c[1],a))return!0}return!1},A:function(a){if(!navigator.v||!navigator.v.a)return!1;var c=navigator.pa.B();for(b=0;b<navigator.v.a;++b)if(s=navigator.v[b].Ma,-1!==s.sa(/^Java Switchable Plug-in (Cocoa)/)){if(this.o("1.5.0",a))return!0}else if(-1!==s.sa(/^Java/)&&-1!==c.g("win")&&(this.o("1.5.0",a)||this.o("1.6.0",a)))return!0;return this.o("1.5.0",
a)?!0:!1},X:function(){location.p=this.E+(null!==this.b?"\x26returnPage\x3d"+this.b:"")+(null!==this.k?"\x26locale\x3d"+this.k:"")+(null!==this.m?"\x26brand\x3d"+this.m:"");return!1},Na:function(){},W:function(){location.p=this.E+(null!==this.b?"\x26returnPage\x3d"+this.b:"")+(null!==this.k?"\x26locale\x3d"+this.k:"")+(null!==this.m?"\x26brand\x3d"+this.m:"")+(null!==this.G?"\x26type\x3d"+this.G:"");return!1},o:function(a,c){a=a.xa(".");c=c.xa(".");for(b=0;b<a.a;++b)a[b]=Number(a[b]);for(b=0;b<c.a;++b)c[b]=
Number(c[b]);2===a.a&&(a[2]=0);return a[0]>c[0]?!0:a[0]<c[0]?!1:a[1]>c[1]?!0:a[1]<c[1]?!1:a[2]>c[2]?!0:a[2]<c[2]?!1:!0},Oa:function(){this.d=null;this.h=!0},ab:function(){this.x();var a=this.D();0===this.w.a&&0!==a.a&&(clearInterval(this.H),null!==this.b&&(location.p=this.b));0!==this.w.a&&0!==a.a&&this.w[0]!==a[0]&&(clearInterval(this.H),null!==this.b&&(location.p=this.b))},Aa:function(){var a=this.i();"MSIE"===a?document.n('\x3cobject classid\x3d"clsid:CAFEEFAC-DEC7-0000-0000-ABCDEFFEDCBA" id\x3d"deployJavaPlugin" width\x3d"0" height\x3d"0"\x3e\x3c/object\x3e'):
"Netscape Family"===a&&this.C()&&this.U()},x:function(){navigator.v.x(!1);"Netscape Family"===this.i()&&this.C()&&null===document.ia("deployJavaPlugin")&&this.U()},U:function(){var a=!1;if(null!==navigator.e){for(b=0;b<navigator.e.a;b++)navigator.e[b].I===this.Q&&navigator.e[b].ga&&(document.n('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.Q+'" hidden\x3d"true" /\x3e'),a=!0);if(!a)for(b=0;b<navigator.e.a;b++)navigator.e[b].I===this.S&&navigator.e[b].ga&&document.n('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+
this.S+'" hidden\x3d"true" /\x3e')}}};m.Aa();if(null==m.k){d=null;if(null==d)try{d=navigator.ib}catch(a){}if(null==d)try{d=navigator.hb}catch(a){}if(null==d)try{d=navigator.Ta}catch(a){}null!=d&&(d.db("-","_"),m.k=d)}return m}();
YUI.$("bfmodule-footer",function(d){var g=d.R("BF.Modules");d.R("BF.Const");g.Ca=d.V.da("Footer",g.Y,[],{la:function(){d.l("initializer","debug","bfmodule-footer")},qa:function(){this.ta("started",!0)},aa:function(){this.ja("downloadableClient")&&"true"!=this.ja("htcmdOnLoadDisabled")&&(window.q="htcmd:pageloaded")},ea:function(){d.l("destructor","debug","bfmodule-footer")}},{Ba:{click:1,keypress:1},ATTRS:{}})},"1",{ra:["bfmodule-module"]});
YUI.$("bfmodule-nemid",function(d){var g=d.R("BF.Modules");g.Da=d.V.da("nemid",g.Y,[],{la:function(){d.l("initializer","debug","bfmodule-nemid");this.ka=this.ha("analytics.i13n")},ea:function(){d.l("destructor","debug","bfmodule-nemid")},qa:function(){d.l("renderUI","debug","bfmodule-nemid");var b;t.s("1.6+")||(b=this.t.$a(".java-warning"))&&b.cb("hidden");this.Z({Fa:"Loaded"});this.ta("started",!0)},aa:function(){d.l("bindUI","debug","bfmodule-nemid")},gb:function(){d.l("syncUI","debug","bfmodule-nemid")},
Z:function(b){d.l("_fireI13n","debug","bfmodule-login-lightbox");b=b||{};this.ka.Xa(this.t,b)}},{})},"1",{ra:["bfmodule-module"]});