var p=function(){var c=["id","class","title","style"];"classid codebase codetype data type archive declare standby height width usemap name tabindex align border hspace vspace".split(" ").ca(c,["lang","dir"],"onclick ondblclick onmousedown onmouseup onmouseover onmousemove onmouseout onkeypress onkeydown onkeyup".split(" "));var h="codebase code name archive object width height alt align hspace vspace".split(" ").ca(c),b,m={h:null,u:null,H:null,w:null,b:null,m:null,k:null,G:null,K:!1,L:null,E:"http://java.sun.com/webapps/getjava/BrowserRedirect?host\x3djava.com",
Ha:"http://www.apple.com/support/downloads/",S:"application/npruntime-scriptable-plugin;DeploymentToolkit",Q:"application/java-deployment-toolkit",P:"http://java.sun.com/products/jfc/tsc/articles/swing2d/webstart.png",d:null,c:null,D:function(){var a=[];if(this.j()){var f=this.f().oa;for(b=0;b<f.Qa();b++)a[b]=f.ha(b).jb}else f=this.i(),"MSIE"===f?this.y("1.7.0")?a[0]="1.7.0":this.y("1.6.0")?a[0]="1.6.0":this.y("1.5.0")?a[0]="1.5.0":this.y("1.4.2")?a[0]="1.4.2":this.ya()&&(a[0]="1.1"):"Netscape Family"===
f&&(this.M(),null!==this.u?a[0]=this.u:this.z("1.7")?a[0]="1.7.0":this.z("1.6")?a[0]="1.6.0":this.z("1.5")?a[0]="1.5.0":this.z("1.4.2")?a[0]="1.4.2":"Safari"===this.c&&(this.A("1.7.0")?a[0]="1.7.0":this.A("1.6")?a[0]="1.6.0":this.A("1.5")?a[0]="1.5.0":this.A("1.4.2")&&(a[0]="1.4.2")));if(this.h)for(b=0;b<a.a;++b)alert("We claim to have detected Java SE "+a[b]);return a},F:function(a,b){return this.j()?this.f().F(a,b)?(this.x(),null!==this.b&&(document.q=this.b),!0):!1:this.N()},N:function(a){if(this.j())return this.f().N(a)?
(this.x(),null!==this.b&&(document.q=this.b),!0):!1;a=this.i();var b=navigator.pa.B();if("true"===this.K&&-1!==b.g("win")&&null!==this.L)this.w=this.D(),null!==this.b&&(this.H=setInterval("deployJava.poll()",3E3)),location.p=this.L;else{if("MSIE"===a)return this.X();if("Netscape Family"===a&&-1!==b.g("win32"))return this.W();location.p=this.E+(null!==this.b?"\x26returnPage\x3d"+this.b:"")+(null!==this.k?"\x26locale\x3d"+this.k:"")+(null!==this.m?"\x26brand\x3d"+this.m:"")}return!1},eb:function(a,
b,d){if("undefined"===d||null===d)d="1.1";var e=d.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");null===this.b&&(this.b=document.q);null!==e?"?"!==this.i()&&"Safari"!==this.c?this.s(d+"+")?this.J(a,b):this.F(d+"+")&&this.J(a,b):this.J(a,b):this.h&&alert("Invalid minimumVersion argument to runApplet():"+d)},J:function(a,f){var d="\x3capplet ",e="",c=!0;if(null===f||"object"!==typeof f)f={};for(var g in a){var k;a:{k=h;var m=g.B(),n=k.a;for(b=0;b<n;b++)if(k[b]===m){k=!0;break a}k=!1}k?(d+=" "+
g+'\x3d"'+a[g]+'"',"code"===g&&(c=!1)):f[g]=a[g]}g=!1;for(var l in f){"codebase_lookup"===l&&(g=!0);if("object"===l||"java_object"===l||"java_code"===l)c=!1;e+='\x3cparam name\x3d"'+l+'" value\x3d"'+f[l]+'"/\x3e'}g||(e+='\x3cparam name\x3d"codebase_lookup" value\x3d"false"/\x3e');c&&(d+=' code\x3d"dummy"');document.n(d+"\x3e\n"+e+"\n\x3c/applet\x3e")},s:function(a){index=0;var f=a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?(\\*|\\+)?$");if(null!==f){a=!0;var d=[];for(b=1;b<f.a;++b)"string"===
typeof f[b]&&""!==f[b]&&(d[index]=f[b],index++);"+"===d[d.a-1]?(a=!1,d.a--):"*"===d[d.a-1]&&d.a--;f=this.D();for(b=0;b<f.a;++b)if(this.ba(f[b],d,a))return!0}else alert("Invalid versionPattern passed to versionCheck: "+a);return!1},O:function(a){if("?"===this.i()||"Safari"===this.c)return!0;if("undefined"===a||null===a)a="1.4.2";var b=!1;null!==a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$")?b=this.s(a+"+"):(this.h&&alert("Invalid minimumVersion argument to isWebStartInstalled(): "+a),b=this.s("1.4.2+"));
return b},M:function(){for(b=0;b<navigator.e.a;++b){var a=navigator.e[b].I.r(/^application\/x-java-applet;jpi-version=(.*)$/);if(null!==a&&(this.u=a[1],"Opera"!==this.c))break}},Va:function(a){navigator.za.B();this.M();if(!1===this.O("1.7.0")&&(!1===this.F("1.7.0+")||!1===this.O("1.7.0")))return!1;var b=null;document.fa&&(b=document.fa);null===b&&(b=document.Ea);var d=this.i(),c;"MSIE"===d?c='\x3cobject classid\x3d"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" width\x3d"0" height\x3d"0"\x3e\x3cPARAM name\x3d"launchjnlp" value\x3d"'+
a+'"\x3e\x3cPARAM name\x3d"docbase" value\x3d"'+b+'"\x3e\x3c/object\x3e':"Netscape Family"===d&&(c='\x3cembed type\x3d"application/x-java-applet;jpi-version\x3d'+this.u+'" width\x3d"0" height\x3d"0" launchjnlp\x3d"'+a+'"docbase\x3d"'+b+'" /\x3e');"undefined"===document.t||null===document.t?(document.n(c),document.q=b):(a=document.Ja("div"),a.Ra="div1",a.T.bb="relative",a.T.Wa="-10000px",a.T.Ya="0px auto",a.Ia="dynamicDiv",a.Sa=c,document.t.Ga(a))},La:function(a){null===this.b&&(this.b=a);document.n('\x3ca href\x3d"'+
("javascript:deployJava.launchWebStartApplication('"+a+"');")+'" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"'+this.P+'" border\x3d"0" /\x3e\x3c/a\x3e')},Ka:function(a,b){null===this.b&&(this.b=a);document.n('\x3ca href\x3d"'+("javascript:if (!deployJava.isWebStartInstalled(\x26quot;"+b+"\x26quot;)) {if (deployJava.installLatestJRE()) {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}} else {if (deployJava.launch(\x26quot;"+a+"\x26quot;)) {}}")+'" onMouseOver\x3d"window.status\x3d\'\'; return true;"\x3e\x3cimg src\x3d"'+
this.P+'" border\x3d"0" /\x3e\x3c/a\x3e')},Ua:function(a){document.q=a;return!0},j:function(){var a=this.f();return a&&a.oa?!0:!1},ma:function(){return this.j()?this.f().ma():!1},va:function(){return this.j()?this.f().va():!1},wa:function(a){this.G=a;return this.j()?this.f().wa(a):!1},ua:function(a){return this.j()?this.f().ua(a):!1},fb:function(a){this.K=a},na:function(){if(this.j()&&this.s("1.6.0_10+"))try{return this.f().na()}catch(a){}return!1},C:function(){this.i();return"Safari"!==this.c&&"Opera"!==
this.c},f:function(){var a=null;this.C()&&(a=document.ia("deployJavaPlugin"));return a},ba:function(a,c,d){var e=a.r("^(\\d+)(?:\\.(\\d+)(?:\\.(\\d+)(?:_(\\d+))?)?)?$");if(null!==e){index=0;a=[];for(b=1;b<e.a;++b)"string"===typeof e[b]&&""!==e[b]&&(a[index]=e[b],index++);e=Math.Za(a.a,c.a);if(d)for(b=0;b<e;++b){if(a[b]!==c[b])return!1}else for(b=0;b<e;++b){if(a[b]<c[b])return!1;if(a[b]>c[b])break}return!0}return!1},i:function(){if(null===this.d){var a=navigator.za.B();this.h&&alert("userAgent -\x3e "+
a);-1!==a.g("msie")?this.c=this.d="MSIE":-1!==a.g("iphone")?(this.d="Netscape Family",this.c="iPhone"):-1!==a.g("firefox")?(this.d="Netscape Family",this.c="Firefox"):-1!==a.g("chrome")?(this.d="Netscape Family",this.c="Chrome"):-1!==a.g("safari")?(this.d="Netscape Family",this.c="Safari"):-1!==a.g("mozilla")?(this.d="Netscape Family",this.c="Other"):-1!==a.g("opera")?(this.d="Netscape Family",this.c="Opera"):(this.d="?",this.c="unknown");this.h&&alert("Detected browser name:"+this.d+", "+this.c)}return this.d},
y:function(a){a="JavaWebStart.isInstalled."+a+".0";if(!ActiveXObject)return this.h&&alert("Browser claims to be IE, but no ActiveXObject object?"),!1;try{return null!==new ActiveXObject(a)}catch(b){return!1}},ya:function(){if("undefined"!==typeof oClientCaps){var a=oClientCaps.Pa("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}","ComponentID");return""===a||"5,0,5000,0"===a?!1:!0}return!1},z:function(a){if(!navigator.e)return this.h&&alert("Browser claims to be Netscape family, but no mimeTypes[] array?"),
!1;for(b=0;b<navigator.e.a;++b){s=navigator.e[b].I;var c=s.r(/^application\/x-java-applet\x3Bversion=(1\.8|1\.7|1\.6|1\.5|1\.4\.2)$/);if(null!==c&&this.o(c[1],a))return!0}return!1},A:function(a){if(!navigator.v||!navigator.v.a)return!1;var c=navigator.pa.B();for(b=0;b<navigator.v.a;++b)if(s=navigator.v[b].Ma,-1!==s.sa(/^Java Switchable Plug-in (Cocoa)/)){if(this.o("1.5.0",a))return!0}else if(-1!==s.sa(/^Java/)&&-1!==c.g("win")&&(this.o("1.5.0",a)||this.o("1.6.0",a)))return!0;return this.o("1.5.0",
a)?!0:!1},X:function(){location.p=this.E+(null!==this.b?"\x26returnPage\x3d"+this.b:"")+(null!==this.k?"\x26locale\x3d"+this.k:"")+(null!==this.m?"\x26brand\x3d"+this.m:"");return!1},Na:function(){},W:function(){location.p=this.E+(null!==this.b?"\x26returnPage\x3d"+this.b:"")+(null!==this.k?"\x26locale\x3d"+this.k:"")+(null!==this.m?"\x26brand\x3d"+this.m:"")+(null!==this.G?"\x26type\x3d"+this.G:"");return!1},o:function(a,c){var d=a.xa("."),e=c.xa(".");for(b=0;b<d.a;++b)d[b]=Number(d[b]);for(b=0;b<
e.a;++b)e[b]=Number(e[b]);2===d.a&&(d[2]=0);return d[0]>e[0]?!0:d[0]<e[0]?!1:d[1]>e[1]?!0:d[1]<e[1]?!1:d[2]>e[2]?!0:d[2]<e[2]?!1:!0},Oa:function(){this.d=null;this.h=!0},ab:function(){this.x();var a=this.D();0===this.w.a&&0!==a.a&&(clearInterval(this.H),null!==this.b&&(location.p=this.b));0!==this.w.a&&0!==a.a&&this.w[0]!==a[0]&&(clearInterval(this.H),null!==this.b&&(location.p=this.b))},Aa:function(){var a=this.i();"MSIE"===a?document.n('\x3cobject classid\x3d"clsid:CAFEEFAC-DEC7-0000-0000-ABCDEFFEDCBA" id\x3d"deployJavaPlugin" width\x3d"0" height\x3d"0"\x3e\x3c/object\x3e'):
"Netscape Family"===a&&this.C()&&this.U()},x:function(){navigator.v.x(!1);"Netscape Family"===this.i()&&this.C()&&null===document.ia("deployJavaPlugin")&&this.U()},U:function(){var a=!1;if(null!==navigator.e){for(b=0;b<navigator.e.a;b++)navigator.e[b].I===this.Q&&navigator.e[b].ga&&(document.n('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+this.Q+'" hidden\x3d"true" /\x3e'),a=!0);if(!a)for(b=0;b<navigator.e.a;b++)navigator.e[b].I===this.S&&navigator.e[b].ga&&document.n('\x3cembed id\x3d"deployJavaPlugin" type\x3d"'+
this.S+'" hidden\x3d"true" /\x3e')}}};m.Aa();if(null==m.k){c=null;if(null==c)try{c=navigator.ib}catch(a){}if(null==c)try{c=navigator.hb}catch(a){}if(null==c)try{c=navigator.Ta}catch(a){}null!=c&&(c.db("-","_"),m.k=c)}return m}();
YUI.$("bfmodule-footer",function(c){var h=c.R("BF.Modules");c.R("BF.Const");h.Ca=c.V.da("Footer",h.Y,[],{la:function(){c.l("initializer","debug","bfmodule-footer")},qa:function(){this.ta("started",!0)},aa:function(){this.ja("downloadableClient")&&"true"!=this.ja("htcmdOnLoadDisabled")&&(window.q="htcmd:pageloaded")},ea:function(){c.l("destructor","debug","bfmodule-footer")}},{Ba:{click:1,keypress:1},ATTRS:{}})},"1",{ra:["bfmodule-module"]});
YUI.$("bfmodule-nemid",function(c){var h=c.R("BF.Modules");h.Da=c.V.da("nemid",h.Y,[],{la:function(){c.l("initializer","debug","bfmodule-nemid");this.ka=this.ha("analytics.i13n")},ea:function(){c.l("destructor","debug","bfmodule-nemid")},qa:function(){c.l("renderUI","debug","bfmodule-nemid");var b;p.s("1.6+")||(b=this.t.$a(".java-warning"))&&b.cb("hidden");this.Z({Fa:"Loaded"});this.ta("started",!0)},aa:function(){c.l("bindUI","debug","bfmodule-nemid")},gb:function(){c.l("syncUI","debug","bfmodule-nemid")},
Z:function(b){c.l("_fireI13n","debug","bfmodule-login-lightbox");b=b||{};this.ka.Xa(this.t,b)}},{})},"1",{ra:["bfmodule-module"]});